spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookingmusical?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234